version: '1'
services:
  quart:
    image: dockerhub.ase.in.tum.de:5043/ios19kirch/api:latest
    container_name: 
    restart: always
    ports:
      - "80:80"
  mongo-db:
    image: mongo
    container_name: mongo-db
    restart: always
    volumes:
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example