version: '3.7'

services:
  db:
    image: mongo
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    environment:
      MONGO_INITDB_DATABASE: "mongo-db"
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "example"
    networks:
      reverse_proxy:
        aliases:
          - koairy_container

  backend:
    build:
      dockerfile: Dockerfile
      context: ./koairy-backend
    container_name: "koairy-backend"
    env_file:
      - ./koairy-backend/.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      reverse_proxy:
        aliases:
          - koairy_container

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./koairy-frontend
    container_name: "koairy-frontend"
    ports:
      - "3000:3000"
    networks:
      reverse_proxy:
        aliases:
          - koairy_container
    command: bash -c "npm install && npm run client"

networks:
  reverse_proxy:
    external: true
    name: reverse_proxy
