version: '3'

services:
  db:
    image: mongo
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    environment:
      MONGO_INITDB_DATABASE: "mongo-db"
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "example"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
#      MONGO_INITDB_DATABASE: mongo-db
  backend:
    build:
      dockerfile: Dockerfile
      context: ./koairy-backend
    image: koairy-backend:latest
    env_file:
      - ./koairy-backend/.env
    depends_on:
      - db
    ports:
      - "8000:8000"
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./koairy-frontend
    image: koairy-frontend:latest
    depends_on:
      - db
    ports:
      - "5000:5000"
