# Copyright (C) 2008, ENPC - INRIA - EDF R&D
#
# This file is part of the air quality modeling system Polyphemus.
#
# Polyphemus is developed in the INRIA - ENPC joint project-team CLIME and in
# the ENPC - EDF R&D joint laboratory CEREA.
#
# Polyphemus is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# Polyphemus is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.
#
# For more information, visit the Polyphemus web site:
#      http://cerea.enpc.fr/polyphemus/

# Put the path to Polyphemus.
# Also editable from command line with option "polyphemus".
polyphemus_path = "../../"

# Include paths: put the absolute paths, the relative paths or the paths into
# the Polyphemus directory.
include_path = """include/Talos
                  include/SeldonData
                  include/AtmoData
                  include/isorropia_aec
                  include/newran
                  include/modules/common
                  include/modules/aerosol
                  include/modules/aerosol/Aerosol_SIREAM_H2O
                  include/modules/aerosol/Aerosol_SIREAM_H2O/INC
                  include/modules/aerosol/Aerosol_SIREAM_H2O/CHEMISTRY/racm
                  include/modules/aerosol/Aerosol_SIREAM_H2O/CHEMISTRY/common
                  include/modules/aerosol/Aerosol_SIREAM_H2O/H2O
                  include/modules/aerosol/Aerosol_SIREAM_H2O/SIMPLE_AQUEOUS
                  include/modules/aerosol/Aerosol_SIREAM_H2O/VSRM
                  include/modules/aerosol/Aerosol_SIREAM_H2O/SIREAM
                  include/models
                  include/driver/common
                  include/driver/common/output_saver
                  include/driver/local
                  include/driver/uncertainty
                  """

# [Optional] Compiled library paths: put absolute paths, relative paths or
# paths that are in the Polyphemus directory. Put the list of paths to
# compiled libraries that may not be installed in your system root.
library_path = None

exclude_dependency = ["typeaoutput\.c", "typeboutput\.c", "read_shm\.c",
                      "set_shm\.c", "write_shm\.c", "read_shm_aer\.c",
                      "write_shm_aer\.c" ]

# Hack in GaussianPuffChemistry.
preprocessor_defines = ["POLYPHEMUS_WITH_AEROSOL_MODULE"]

SConscript(polyphemus_path + "/scons/main")(globals())
