
version: '3'

services:
  db:
    image: mongo
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    env_file:
      - .env
  web_app:
    build:
      dockerfile: Dockerfile
      context: .
    image: fastapi_image:latest
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
